### ISSUE TITLE
burnable stone

### ISSUE THREAD

**Issue by BETLOG** [Wacky-Mole/WackysDatabase#24]
I'm having an issue with valkea stone blocks being flammable, and tried to fix it with wacky.
[According to OrianaVenture](https://discord.com/channels/830496756801863742/830545339890532402/1363703910568693992) I need to be adding/modifying `m_burnable`, but despite testing multiple variants of that it in various places under the `wearNTearData` heirarchy... it seems wacky doesnt recognise the variable and ignores it... or I simply have the wrong syntax/placement.
https://github.com/The-Bees-Decree-Server/VALKEA/issues/41

Based on OV's discord responses this seems like  the most likely syntax, but only one of half a dozen i tried
```
name: piece_SmtStoneBlock4
piecehammer: Hammer
m_name: Smooth Stone Block V
sizeMultiplier: 1
m_description: Smooth. Block. Test. WACKYDB'd .
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_stonecutter
piecehammerCategory: ValkeaBuildII BuildingWorkbench
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 5
  damageModifiers:
    m_burnable: Immune
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Normal
    m_chop: Normal
    m_pickaxe: Weak
    m_fire: Immune
    m_frost: Immune
    m_lightning: Immune
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
  materialType: Stone
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
shieldGenData: 
batteringRamData: 
build:
- Stone:6:1:True

```
